In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/merged2.csv")

In [ ]:
df.head()

,Unnamed: 0,id,screen_name,time,link,text,source,user_id,date_file,account_id,account_screen_name,account_account_type,meta_name,meta_chamber,meta_type,meta_party,Clean_Text
0,0,877383834240667648,KamalaHarris,2017-06-21 00:33:01-04:00,https://www.twitter.com/KamalaHarris/statuses/...,No public hearings. \nNo debate. \nNo text.\nN...,Sprout Social,30354991,2017-06-21.json,30354991,KamalaHarris,campaign,Kamala Harris,senate,member,D,no public hearings no debate no textno transpa...
1,1,877376225664090112,tedlieu,2017-06-21 00:02:47-04:00,https://www.twitter.com/tedlieu/statuses/87737...,Why should world leaders trust or listen to US...,Twitter for Android,21059255,2017-06-21.json,21059255,tedlieu,campaign,Ted Lieu,house,member,D,why should world leaders trust or listen to us...
2,2,877405817565306880,JerryNadler,2017-06-21 02:00:22-04:00,https://www.twitter.com/JerryNadler/statuses/8...,Congratulations to Jon @ossoff and #GADems on ...,Twitter for iPhone,408816873,2017-06-21.json,408816873,JerryNadler,campaign,Jerrold Nadler,house,member,D,congratulations to jon <OTHER_USER> and gadems...
3,3,877400668411052032,TulsiGabbard,2017-06-21 01:39:55-04:00,https://www.twitter.com/TulsiGabbard/statuses/...,Join me in celebrating the gift of yoga on thi...,Twitter for iPhone,26637348,2017-06-21.json,26637348,TulsiGabbard,campaign,Tulsi Gabbard,house,member,D,join me in celebrating the gift of yoga on thi...
4,4,877409109846478848,JerryNadler,2017-06-21 02:13:27-04:00,https://www.twitter.com/JerryNadler/statuses/8...,#GA06 is #GOP stronghold &amp; @ossoff nearly ...,Twitter for iPhone,408816873,2017-06-21.json,408816873,JerryNadler,campaign,Jerrold Nadler,house,member,D,ga06 is gop stronghold amp <OTHER_USER> nearly...

In [ ]:
df.shape

(20416, 17)

In [ ]:
df.drop("Unnamed: 0", axis = 1, inplace = True)
df.head()

,id,screen_name,time,link,text,source,user_id,date_file,account_id,account_screen_name,account_account_type,meta_name,meta_chamber,meta_type,meta_party,Clean_Text
0,877383834240667648,KamalaHarris,2017-06-21 00:33:01-04:00,https://www.twitter.com/KamalaHarris/statuses/...,No public hearings. \nNo debate. \nNo text.\nN...,Sprout Social,30354991,2017-06-21.json,30354991,KamalaHarris,campaign,Kamala Harris,senate,member,D,no public hearings no debate no textno transpa...
1,877376225664090112,tedlieu,2017-06-21 00:02:47-04:00,https://www.twitter.com/tedlieu/statuses/87737...,Why should world leaders trust or listen to US...,Twitter for Android,21059255,2017-06-21.json,21059255,tedlieu,campaign,Ted Lieu,house,member,D,why should world leaders trust or listen to us...
2,877405817565306880,JerryNadler,2017-06-21 02:00:22-04:00,https://www.twitter.com/JerryNadler/statuses/8...,Congratulations to Jon @ossoff and #GADems on ...,Twitter for iPhone,408816873,2017-06-21.json,408816873,JerryNadler,campaign,Jerrold Nadler,house,member,D,congratulations to jon <OTHER_USER> and gadems...
3,877400668411052032,TulsiGabbard,2017-06-21 01:39:55-04:00,https://www.twitter.com/TulsiGabbard/statuses/...,Join me in celebrating the gift of yoga on thi...,Twitter for iPhone,26637348,2017-06-21.json,26637348,TulsiGabbard,campaign,Tulsi Gabbard,house,member,D,join me in celebrating the gift of yoga on thi...
4,877409109846478848,JerryNadler,2017-06-21 02:13:27-04:00,https://www.twitter.com/JerryNadler/statuses/8...,#GA06 is #GOP stronghold &amp; @ossoff nearly ...,Twitter for iPhone,408816873,2017-06-21.json,408816873,JerryNadler,campaign,Jerrold Nadler,house,member,D,ga06 is gop stronghold amp <OTHER_USER> nearly...

In [ ]:
!pip install transformers

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (4.57.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.20.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.35.3)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers) (2.32.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.6.2)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (2025.3.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (1.1.10)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2025.10.5)

In [ ]:
from transformers import pipeline

In [ ]:
chosen_model = "distilbert-base-uncased-finetuned-sst-2-english"
distil_bert = pipeline(task="sentiment-analysis", model=chosen_model, device = 0, batch_size = 32)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

Device set to use cuda:0

In [ ]:
print(df["Clean_Text"].head())
print(df["Clean_Text"].apply(type).value_counts())

0    no public hearings no debate no textno transpa...
1    why should world leaders trust or listen to us...
2    congratulations to jon <OTHER_USER> and gadems...
3    join me in celebrating the gift of yoga on thi...
4    ga06 is gop stronghold amp <OTHER_USER> nearly...
Name: Clean_Text, dtype: object
Clean_Text
<class 'str'>      20389
<class 'float'>       27
Name: count, dtype: int64

In [ ]:
df["Clean_Text"] = df["Clean_Text"].astype("str")

In [ ]:
print(df["Clean_Text"].str.len().value_counts())

Clean_Text
113    434
114    429
134    420
112    405
135    402
      ...
5        1
7        1
351      1
294      1
364      1
Name: count, Length: 312, dtype: int64

In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
df[df["Clean_Text"].str.len() < 10]

,id,screen_name,time,link,text,source,user_id,date_file,account_id,account_screen_name,account_account_type,meta_name,meta_chamber,meta_type,meta_party,Clean_Text
90,877503448773734400,RepTimMurphy,2017-06-21 08:28:20-04:00,https://www.twitter.com/RepTimMurphy/statuses/...,https://t.co/qQOGkpPvh0,Twitter Web Client,117777832,2017-06-21.json,117777832,RepTimMurphy,office,Tim Murphy,house,member,R,nan
1042,877579193273528320,RepSanfordSC,2017-06-21 13:29:18-04:00,https://www.twitter.com/RepSanfordSC/statuses/...,https://t.co/mqqFsEmpLx,Facebook,1499993378,2017-06-21.json,1499993378,RepSanfordSC,office,Mark Sanford,house,member,R,nan
2417,877678781816872960,RepWilson,2017-06-21 20:05:02-04:00,https://www.twitter.com/RepWilson/statuses/877...,https://t.co/p2EPiNjaQX,Twitter for iPhone,234014087,2017-06-21.json,234014087,RepWilson,office,Frederica Wilson,house,member,D,nan
3283,877906011377602560,RobWittman,2017-06-22 11:07:58-04:00,https://www.twitter.com/RobWittman/statuses/87...,https://t.co/EUadovXZfZ,Twitter for iPhone,15356407,2017-06-22.json,15356407,RobWittman,office,Rob Wittman,house,member,R,nan
3472,877925969662812160,RepEspaillat,2017-06-22 12:27:16-04:00,https://www.twitter.com/RepEspaillat/statuses/...,https://t.co/NHW3r1mXHT,Twitter Web Client,817076257770835968,2017-06-22.json,817076257770835968,RepEspaillat,office,Adriano Espaillat,house,member,D,nan
4246,877978023550693376,RepAdamSmith,2017-06-22 15:54:07-04:00,https://www.twitter.com/RepAdamSmith/statuses/...,https://t.co/5zJJdSVunP,Twitter for iPhone,58928690,2017-06-22.json,58928690,RepAdamSmith,office,Adam Smith,house,member,D,nan
4294,877975701726605313,RepPaulTonko,2017-06-22 15:44:53-04:00,https://www.twitter.com/RepPaulTonko/statuses/...,https://t.co/bnaJyTHAGE,TweetDeck,84119348,2017-06-22.json,84119348,RepPaulTonko,office,Paul Tonko,house,member,D,nan
4684,877984620104609797,RepScottTaylor,2017-06-22 16:20:20-04:00,https://www.twitter.com/RepScottTaylor/statuse...,https://t.co/WgXI3jcsCZ,Twitter for iPhone,837722935095930883,2017-06-22.json,837722935095930883,RepScottTaylor,office,Scott Taylor,house,member,R,nan
5248,878068680441171968,RepBeatty,2017-06-22 21:54:21-04:00,https://www.twitter.com/RepBeatty/statuses/878...,https://t.co/QBek73YJcl,Twitter for iPhone,1531521632,2017-06-22.json,1531521632,RepBeatty,office,Joyce Beatty,house,member,D,nan
5353,878190848625737729,RepLawrence,2017-06-23 05:59:48-04:00,https://www.twitter.com/RepLawrence/statuses/8...,https://t.co/9ogwm4HiUi https://t.co/Aw7QTBsFC0,Facebook,2863006655,2017-06-23.json,2863006655,RepLawrence,office,Brenda Lawrence,house,member,D,
5423,878230148981575681,RepDannyDavis,2017-06-23 08:35:58-04:00,https://www.twitter.com/RepDannyDavis/statuses...,https://t.co/XJwYMP5lVT,Twitter for Android,789244177,2017-06-23.json,789244177,RepDannyDavis,office,Danny K. Davis,house,member,D,nan
7003,878382633729769472,RepWilson,2017-06-23 18:41:54-04:00,https://www.twitter.com/RepWilson/statuses/878...,https://t.co/CG8Mkmznc8,Twitter Web Client,234014087,2017-06-23.json,234014087,RepWilson,office,Frederica Wilson,house,member,D,nan
8118,879066500950364160,CaptClayHiggins,2017-06-25 15:59:20-04:00,https://www.twitter.com/CaptClayHiggins/status...,Cindy... https://t.co/BBfxOA3VLz,Facebook,3298489662,2017-06-25.json,1011053278304591872,CaptClayHiggins,campaign,Clay Higgins,house,member,R,cindy
8288,879121951075205122,JohnCornyn,2017-06-25 19:39:41-04:00,https://www.twitter.com/JohnCornyn/statuses/87...,https://t.co/uiRiIuLoWW,Twitter for iPad,13218102,2017-06-25.json,13218102,JohnCornyn,office,John Cornyn,senate,member,R,nan
10111,879445173721341952,RepSpeier,2017-06-26 17:04:03-04:00,https://www.twitter.com/RepSpeier/statuses/879...,https://t.co/blI4YwN2L3,Twitter Web Client,24913074,2017-06-26.json,24913074,RepSpeier,office,Jackie Speier,house,member,D,nan
11095,879713152396660736,RepJeffries,2017-06-27 10:48:54-04:00,https://www.twitter.com/RepJeffries/statuses/8...,Facts. http://pbs.twimg.com/media/DDVeaeMXoAYV...,Twitter Web Client,467823431,2017-06-27.json,467823431,RepJeffries,office,Hakeem Jeffries,house,member,D,facts
11571,879743526828945409,RepScottTaylor,2017-06-27 12:49:36-04:00,https://www.twitter.com/RepScottTaylor/statuse...,https://taylor.house.gov/media/press-releases/...,Twitter Web Client,837722935095930883,2017-06-27.json,837722935095930883,RepScottTaylor,office,Scott Taylor,house,member,R,nan
11823,879749605675630592,RepMattGaetz,2017-06-27 13:13:45-04:00,https://www.twitter.com/RepMattGaetz/statuses/...,http://pbs.twimg.com/media/DDV_lupWsAAYKLN.jpg,Twitter Web Client,818948638890217473,2017-06-27.json,818948638890217473,RepMattGaetz,office,Matt Gaetz,house,member,R,nan
12338,879762625168629762,RepMattGaetz,2017-06-27 14:05:29-04:00,https://www.twitter.com/RepMattGaetz/statuses/...,http://pbs.twimg.com/media/DDWLcHJXoAAGC4L.jpg,Twitter Web Client,818948638890217473,2017-06-27.json,818948638890217473,RepMattGaetz,office,Matt Gaetz,house,member,R,nan
13630,880020746877186049,JacksonLeeTX18,2017-06-28 07:11:10-04:00,https://www.twitter.com/JacksonLeeTX18/statuse...,http://pbs.twimg.com/media/DDZ2NC6XcAAiiHM.jpg,Hootsuite,80612021,2017-06-28.json,80612021,JacksonLeeTX18,office,Sheila Jackson Lee,house,member,D,nan
13912,880073324566503425,RepMikeBishop,2017-06-28 10:40:06-04:00,https://www.twitter.com/RepMikeBishop/statuses...,https://www.youtube.com/watch?v=8qpu9nubLek&fe...,Twitter Web Client,2914571740,2017-06-28.json,2914571740,RepMikeBishop,office,Mike Bishop,house,member,R,nan
14171,880086743667662851,HASCDemocrats,2017-06-28 11:33:25-04:00,https://www.twitter.com/HASCDemocrats/statuses...,#FY18NDAA http://pbs.twimg.com/media/DDayArIXo...,Twitter Web Client,74294786,2017-06-28.json,74294786,HASCDemocrats,office,House Committee on Armed Services,house,committee,NaN,fy18ndaa
14423,880098575954399233,RepEspaillat,2017-06-28 12:20:26-04:00,https://www.twitter.com/RepEspaillat/statuses/...,http://pbs.twimg.com/media/DDa8-SsW0AAzVAZ.jpg,Twitter Web Client,817076257770835968,2017-06-28.json,817076257770835968,RepEspaillat,office,Adriano Espaillat,house,member,D,nan
15223,880167821870678016,EdRRoyce,2017-06-28 16:55:36-04:00,https://www.twitter.com/EdRRoyce/statuses/8801...,http://pbs.twimg.com/media/DDb79SYVYAARUev.jpg,TweetDeck,182052260,2017-06-28.json,182052260,EdRRoyce,campaign,Ed Royce,house,member,R,nan
16001,880235741808349184,senorrinhatch,2017-06-28 21:25:29-04:00,https://www.twitter.com/senorrinhatch/statuses...,http://pbs.twimg.com/media/DDc5vIVUAAERZUR.jpg...,Twitter for iPhone,262756641,2017-06-28.json,262756641,senorrinhatch,office,Orrin Hatch,senate,member,R,
16027,880243992029519872,senorrinhatch,2017-06-28 21:58:16-04:00,https://www.twitter.com/senorrinhatch/statuses...,http://pbs.twimg.com/media/DDdBPZBXUAA10hq.jpg,Twitter for iPhone,262756641,2017-06-28.json,262756641,senorrinhatch,office,Orrin Hatch,senate,member,R,nan
16059,880237664271826945,senorrinhatch,2017-06-28 21:33:07-04:00,https://www.twitter.com/senorrinhatch/statuses...,http://pbs.twimg.com/media/DDc7e9ZXUAALrPc.jpg,Twitter for iPhone,262756641,2017-06-28.json,262756641,senorrinhatch,office,Orrin Hatch,senate,member,R,nan
16140,880270276780601344,DevinNunes,2017-06-28 23:42:43-04:00,https://www.twitter.com/DevinNunes/statuses/88...,https://amgreatness.com/2017/06/28/late-great-...,Twitter for iPad,344972339,2017-06-28.json,54412900,DevinNunes,office,Devin Nunes,house,member,R,nan
16888,880445379745021953,JohnCornyn,2017-06-29 11:18:31-04:00,https://www.twitter.com/JohnCornyn/statuses/88...,http://pbs.twimg.com/media/DDf4ZtdXkAAvZSW.jpg...,Twitter for iPhone,13218102,2017-06-29.json,13218102,JohnCornyn,office,John Cornyn,senate,member,R,
16973,880469807581208576,RepJayapal,2017-06-29 12:55:35-04:00,https://www.twitter.com/RepJayapal/statuses/88...,http://pbs.twimg.com/media/DDgOm0kUwAAwD_U.jpg,Twitter Web Client,815733290955112448,2017-06-29.json,815733290955112448,RepJayapal,office,Pramila Jayapal,house,member,D,nan
17177,880457643596423172,jasoninthehouse,2017-06-29 12:07:15-04:00,https://www.twitter.com/jasoninthehouse/status...,Bye Bye http://pbs.twimg.com/media/DDgDj0uXkAM...,Twitter for iPhone,17800215,2017-06-29.json,17800215,jasoninthehouse,office,Jason Chaffetz,house,member,R,bye bye
17292,880481000874180609,RepTimMurphy,2017-06-29 13:40:03-04:00,https://www.twitter.com/RepTimMurphy/statuses/...,https://medium.com/@Tim.Murphy/congratulations...,Twitter Web Client,117777832,2017-06-29.json,117777832,RepTimMurphy,office,Tim Murphy,house,member,R,nan
18788,880580975381667841,RepComstock,2017-06-29 20:17:19-04:00,https://www.twitter.com/RepComstock/statuses/8...,#VA10 http://pbs.twimg.com/media/DDhznKpXUAEBl...,Twitter Web Client,2933760046,2017-06-29.json,2933760046,RepComstock,office,Barbara Comstock,house,member,R,va10
19260,880810975930220544,TexansforLamar,2017-06-30 11:31:15-04:00,https://www.twitter.com/TexansforLamar/statuse...,ICYMI: http://ow.ly/9RHD30cK9rM,Twitter for iPhone,1921735968,2017-06-30.json,1921735968,TexansforLamar,campaign,Lamar Smith,house,member,R,icymi
19380,880831539122253824,RepRaulGrijalva,2017-06-30 12:52:58-04:00,https://www.twitter.com/RepRaulGrijalva/status...,http://pbs.twimg.com/media/DDlWNL4XYAAypMU.png,Twitter Web Client,28602948,2017-06-30.json,28602948,RepRaulGrijalva,office,Raul Grijalva,house,member,D,nan
19436,880826436298387456,HouseAdm_Dems,2017-06-30 12:32:42-04:00,https://www.twitter.com/HouseAdm_Dems/statuses...,https://www.thenation.com/article/the-trump-ad...,Twitter Web Client,19716781,2017-06-30.json,19716781,HouseAdm_Dems,office,House Committee on House Administration,house,committee,NaN,nan

In [ ]:
df1 = df[(df["Clean_Text"].str.len() > 10) & (df["Clean_Text"] != "nan")]

In [ ]:
display(df1.shape)
display(df.shape)
display(df1["Clean_Text"].str.len().value_counts())

(20377, 16)

(20416, 16)

Clean_Text
113    434
114    429
134    420
112    405
135    402
      ...
309      1
316      1
351      1
294      1
364      1
Name: count, Length: 303, dtype: int64

In [ ]:
results = distil_bert(df1["Clean_Text"].tolist())

In [ ]:
results

[{'label': 'NEGATIVE', 'score': 0.9970408082008362},
 {'label': 'NEGATIVE', 'score': 0.9986342787742615},
 {'label': 'POSITIVE', 'score': 0.8995383381843567},
 {'label': 'POSITIVE', 'score': 0.9996635913848877},
 {'label': 'POSITIVE', 'score': 0.9832448959350586},
 {'label': 'NEGATIVE', 'score': 0.9822936654090881},
 {'label': 'POSITIVE', 'score': 0.9973313808441162},
 {'label': 'NEGATIVE', 'score': 0.9744671583175659},
 {'label': 'NEGATIVE', 'score': 0.6447921991348267},
 {'label': 'NEGATIVE', 'score': 0.9967057108879089},
 {'label': 'NEGATIVE', 'score': 0.9874047040939331},
 {'label': 'NEGATIVE', 'score': 0.9945085644721985},
 {'label': 'NEGATIVE', 'score': 0.9997819066047668},
 {'label': 'POSITIVE', 'score': 0.9467873573303223},
 {'label': 'NEGATIVE', 'score': 0.9963178634643555},
 {'label': 'POSITIVE', 'score': 0.9995063543319702},
 {'label': 'NEGATIVE', 'score': 0.9991360306739807},
 {'label': 'POSITIVE', 'score': 0.9985363483428955},
 {'label': 'NEGATIVE', 'score': 0.9980055689811707},
 {'label': 'POSITIVE', 'score': 0.9931151270866394},
 {'label': 'POSITIVE', 'score': 0.7774837613105774},
 {'label': 'NEGATIVE', 'score': 0.9953168630599976},
 {'label': 'NEGATIVE', 'score': 0.9477387070655823},
 {'label': 'POSITIVE', 'score': 0.9944684505462646},
 {'label': 'NEGATIVE', 'score': 0.951133668422699},
 {'label': 'POSITIVE', 'score': 0.9975041747093201},
 {'label': 'NEGATIVE', 'score': 0.9873282313346863},
 {'label': 'NEGATIVE', 'score': 0.9861342310905457},
 {'label': 'NEGATIVE', 'score': 0.983272910118103},
 {'label': 'NEGATIVE', 'score': 0.9836800694465637},
 {'label': 'NEGATIVE', 'score': 0.7319216132164001},
 {'label': 'NEGATIVE', 'score': 0.9782153964042664},
 {'label': 'POSITIVE', 'score': 0.9471463561058044},
 {'label': 'NEGATIVE', 'score': 0.9991030693054199},
 {'label': 'NEGATIVE', 'score': 0.9849268198013306},
 {'label': 'POSITIVE', 'score': 0.9980722665786743},
 {'label': 'POSITIVE', 'score': 0.9678231477737427},
 {'label': 'POSITIVE', 'score': 0.9986225366592407},
 {'label': 'NEGATIVE', 'score': 0.9970476031303406},
 {'label': 'NEGATIVE', 'score': 0.9887866377830505},
 {'label': 'NEGATIVE', 'score': 0.9890671372413635},
 {'label': 'NEGATIVE', 'score': 0.9941309094429016},
 {'label': 'NEGATIVE', 'score': 0.996807336807251},
 {'label': 'NEGATIVE', 'score': 0.8271358013153076},
 {'label': 'POSITIVE', 'score': 0.9403112530708313},
 {'label': 'NEGATIVE', 'score': 0.9995317459106445},
 {'label': 'NEGATIVE', 'score': 0.9991636276245117},
 {'label': 'NEGATIVE', 'score': 0.9997267127037048},
 {'label': 'NEGATIVE', 'score': 0.9735097289085388},
 {'label': 'POSITIVE', 'score': 0.9844576716423035},
 {'label': 'NEGATIVE', 'score': 0.9972699284553528},
 {'label': 'NEGATIVE', 'score': 0.9975625276565552},
 {'label': 'POSITIVE', 'score': 0.9992743134498596},
 {'label': 'POSITIVE', 'score': 0.998684823513031},
 {'label': 'POSITIVE', 'score': 0.9838923215866089},
 {'label': 'POSITIVE', 'score': 0.9110496640205383},
 {'label': 'NEGATIVE', 'score': 0.960318386554718},
 {'label': 'NEGATIVE', 'score': 0.9822205901145935},
 {'label': 'NEGATIVE', 'score': 0.9342140555381775},
 {'label': 'POSITIVE', 'score': 0.8248683214187622},
 {'label': 'NEGATIVE', 'score': 0.9982635378837585},
 {'label': 'POSITIVE', 'score': 0.9997803568840027},
 {'label': 'POSITIVE', 'score': 0.99820876121521},
 {'label': 'NEGATIVE', 'score': 0.9730053544044495},
 {'label': 'POSITIVE', 'score': 0.9947116374969482},
 {'label': 'POSITIVE', 'score': 0.5999913215637207},
 {'label': 'NEGATIVE', 'score': 0.9936233162879944},
 {'label': 'POSITIVE', 'score': 0.9809693098068237},
 {'label': 'NEGATIVE', 'score': 0.9755932092666626},
 {'label': 'NEGATIVE', 'score': 0.9987651109695435},
 {'label': 'POSITIVE', 'score': 0.9395278096199036},
 {'label': 'NEGATIVE', 'score': 0.9983783960342407},
 {'label': 'NEGATIVE', 'score': 0.9996011853218079},
 {'label': 'NEGATIVE', 'score': 0.9870473146438599},
 {'label': 'NEGATIVE', 'score': 0.9992576241493225},
 {'label': 'NEGATIVE', 'score': 0.9687217473983765},
 {'label': 'NEGATIVE', 'score': 0.5702732801437378},
 {'label': 'NEGATIVE', 'score': 0.9994506239891052},
 {'label': 'NEGATIVE', 'score': 0.8296801447868347},
 {'label': 'NEGATIVE', 'score': 0.8495276570320129},
 {'label': 'NEGATIVE', 'score': 0.8854351043701172},
 {'label': 'NEGATIVE', 'score': 0.9828365445137024},
 {'label': 'NEGATIVE', 'score': 0.8593217730522156},
 {'label': 'POSITIVE', 'score': 0.9048141241073608},
 {'label': 'NEGATIVE', 'score': 0.9988943934440613},
 {'label': 'NEGATIVE', 'score': 0.9263564944267273},
 {'label': 'POSITIVE', 'score': 0.9985246062278748},
 {'label': 'POSITIVE', 'score': 0.9988467693328857},
 {'label': 'NEGATIVE', 'score': 0.9862030744552612},
 {'label': 'POSITIVE', 'score': 0.999858021736145},
 {'label': 'POSITIVE', 'score': 0.9172671437263489},
 {'label': 'NEGATIVE', 'score': 0.9984726309776306},
 {'label': 'NEGATIVE', 'score': 0.9982157945632935},
 {'label': 'POSITIVE', 'score': 0.984907865524292},
 {'label': 'NEGATIVE', 'score': 0.9893307685852051},
 {'label': 'NEGATIVE', 'score': 0.9977841973304749},
 {'label': 'NEGATIVE', 'score': 0.9920068383216858},
 {'label': 'NEGATIVE', 'score': 0.9974363446235657},
 {'label': 'POSITIVE', 'score': 0.841220498085022},
 {'label': 'NEGATIVE', 'score': 0.9923887848854065},
 {'label': 'POSITIVE', 'score': 0.7488986253738403},
 {'label': 'NEGATIVE', 'score': 0.9886215329170227},
 {'label': 'POSITIVE', 'score': 0.9943168759346008},
 {'label': 'NEGATIVE', 'score': 0.9987418055534363},
 {'label': 'POSITIVE', 'score': 0.6054064631462097},
 {'label': 'NEGATIVE', 'score': 0.9882489442825317},
 {'label': 'POSITIVE', 'score': 0.9891390204429626},
 {'label': 'NEGATIVE', 'score': 0.9613257050514221},
 {'label': 'POSITIVE', 'score': 0.9974263310432434},
 {'label': 'NEGATIVE', 'score': 0.9992879033088684},
 {'label': 'NEGATIVE', 'score': 0.9920164346694946},
 {'label': 'NEGATIVE', 'score': 0.9571815729141235},
 {'label': 'POSITIVE', 'score': 0.926517903804779},
 {'label': 'NEGATIVE', 'score': 0.9979428648948669},
 {'label': 'NEGATIVE', 'score': 0.9747586250305176},
 {'label': 'POSITIVE', 'score': 0.9417365789413452},
 {'label': 'POSITIVE', 'score': 0.9996374845504761},
 {'label': 'NEGATIVE', 'score': 0.9852199554443359},
 {'label': 'POSITIVE', 'score': 0.7995723485946655},
 {'label': 'NEGATIVE', 'score': 0.9919415712356567},
 {'label': 'NEGATIVE', 'score': 0.998609185218811},
 {'label': 'NEGATIVE', 'score': 0.8283551931381226},
 {'label': 'NEGATIVE', 'score': 0.9733072519302368},
 {'label': 'NEGATIVE', 'score': 0.9584850072860718},
 {'label': 'NEGATIVE', 'score': 0.9995980858802795},
 {'label': 'POSITIVE', 'score': 0.5551937222480774},
 {'label': 'NEGATIVE', 'score': 0.9987542629241943},
 {'label': 'POSITIVE', 'score': 0.9993855953216553},
 {'label': 'NEGATIVE', 'score': 0.6277539134025574},
 {'label': 'NEGATIVE', 'score': 0.9930451512336731},
 {'label': 'NEGATIVE', 'score': 0.984162449836731},
 {'label': 'NEGATIVE', 'score': 0.9920990467071533},
 {'label': 'POSITIVE', 'score': 0.9992852807044983},
 {'label': 'NEGATIVE', 'score': 0.9601722359657288},
 {'label': 'NEGATIVE', 'score': 0.9940724968910217},
 {'label': 'POSITIVE', 'score': 0.9987088441848755},
 {'label': 'POSITIVE', 'score': 0.9946585297584534},
 {'label': 'NEGATIVE', 'score': 0.8957061767578125},
 {'label': 'NEGATIVE', 'score': 0.9967034459114075},
 {'label': 'POSITIVE', 'score': 0.8105572462081909},
 {'label': 'POSITIVE', 'score': 0.937956690788269},
 {'label': 'NEGATIVE', 'score': 0.9803007245063782},
 {'label': 'POSITIVE', 'score': 0.9992166757583618},
 {'label': 'NEGATIVE', 'score': 0.9816853404045105},
 {'label': 'NEGATIVE', 'score': 0.9161742925643921},
 {'label': 'NEGATIVE', 'score': 0.8550059795379639},
 {'label': 'NEGATIVE', 'score': 0.8352939486503601},
 {'label': 'NEGATIVE', 'score': 0.8533990383148193},
 {'label': 'NEGATIVE', 'score': 0.9633006453514099},
 {'label': 'NEGATIVE', 'score': 0.9966930150985718},
 {'label': 'POSITIVE', 'score': 0.999381422996521},
 {'label': 'NEGATIVE', 'score': 0.9992044568061829},
 {'label': 'NEGATIVE', 'score': 0.8170543313026428},
 {'label': 'NEGATIVE', 'score': 0.9701384902000427},
 {'label': 'POSITIVE', 'score': 0.9971606731414795},
 {'label': 'POSITIVE', 'score': 0.9998109936714172},
 {'label': 'NEGATIVE', 'score': 0.9841839075088501},
 {'label': 'POSITIVE', 'score': 0.9758813977241516},
 {'label': 'NEGATIVE', 'score': 0.6920360922813416},
 {'label': 'NEGATIVE', 'score': 0.999424934387207},
 {'label': 'POSITIVE', 'score': 0.9840093851089478},
 {'label': 'NEGATIVE', 'score': 0.9826520681381226},
 {'label': 'POSITIVE', 'score': 0.9279661774635315},
 {'label': 'NEGATIVE', 'score': 0.9912291765213013},
 {'label': 'NEGATIVE', 'score': 0.9993102550506592},
 {'label': 'POSITIVE', 'score': 0.9997958540916443},
 {'label': 'NEGATIVE', 'score': 0.9942567944526672},
 {'label': 'POSITIVE', 'score': 0.9992226362228394},
 {'label': 'POSITIVE', 'score': 0.9984647035598755},
 {'label': 'POSITIVE', 'score': 0.9952465891838074},
 {'label': 'NEGATIVE', 'score': 0.9984412789344788},
 {'label': 'NEGATIVE', 'score': 0.9697928428649902},
 {'label': 'POSITIVE', 'score': 0.9985559582710266},
 {'label': 'NEGATIVE', 'score': 0.97288978099823},
 {'label': 'POSITIVE', 'score': 0.9132175445556641},
 {'label': 'NEGATIVE', 'score': 0.8942208290100098},
 {'label': 'POSITIVE', 'score': 0.9979312419891357},
 {'label': 'POSITIVE', 'score': 0.8833308815956116},
 {'label': 'NEGATIVE', 'score': 0.9669342637062073},
 {'label': 'NEGATIVE', 'score': 0.9910628795623779},
 {'label': 'POSITIVE', 'score': 0.9373871088027954},
 {'label': 'NEGATIVE', 'score': 0.9632239937782288},
 {'label': 'POSITIVE', 'score': 0.9977019429206848},
 {'label': 'NEGATIVE', 'score': 0.9978984594345093},
 {'label': 'NEGATIVE', 'score': 0.9835579991340637},
 {'label': 'NEGATIVE', 'score': 0.9989377856254578},
 {'label': 'NEGATIVE', 'score': 0.9845767617225647},
 {'label': 'POSITIVE', 'score': 0.9679545760154724},
 {'label': 'POSITIVE', 'score': 0.8730370402336121},
 {'label': 'NEGATIVE', 'score': 0.9212927222251892},
 {'label': 'NEGATIVE', 'score': 0.9393875002861023},
 {'label': 'NEGATIVE', 'score': 0.986004650592804},
 {'label': 'POSITIVE', 'score': 0.5744461417198181},
 {'label': 'NEGATIVE', 'score': 0.6271339058876038},
 {'label': 'POSITIVE', 'score': 0.999524712562561},
 {'label': 'NEGATIVE', 'score': 0.9411029815673828},
 {'label': 'NEGATIVE', 'score': 0.6331799030303955},
 {'label': 'POSITIVE', 'score': 0.9997147917747498},
 {'label': 'POSITIVE', 'score': 0.9989221096038818},
 {'label': 'NEGATIVE', 'score': 0.9628169536590576},
 {'label': 'POSITIVE', 'score': 0.9783751368522644},
 {'label': 'POSITIVE', 'score': 0.9740392565727234},
 {'label': 'POSITIVE', 'score': 0.9980204105377197},
 {'label': 'POSITIVE', 'score': 0.9939079284667969},
 {'label': 'POSITIVE', 'score': 0.9990935325622559},
 {'label': 'POSITIVE', 'score': 0.9632629156112671},
 {'label': 'POSITIVE', 'score': 0.9976734519004822},
 {'label': 'POSITIVE', 'score': 0.9558887481689453},
 {'label': 'NEGATIVE', 'score': 0.982813835144043},
 {'label': 'POSITIVE', 'score': 0.9983755350112915},
 {'label': 'NEGATIVE', 'score': 0.9992045760154724},
 {'label': 'NEGATIVE', 'score': 0.9864280819892883},
 {'label': 'NEGATIVE', 'score': 0.9921575784683228},
 {'label': 'NEGATIVE', 'score': 0.9544445276260376},
 {'label': 'POSITIVE', 'score': 0.9954628348350525},
 {'label': 'NEGATIVE', 'score': 0.9980851411819458},
 {'label': 'POSITIVE', 'score': 0.9873641133308411},
 {'label': 'NEGATIVE', 'score': 0.9960881471633911},
 {'label': 'POSITIVE', 'score': 0.99904865026474},
 {'label': 'POSITIVE', 'score': 0.9957314133644104},
 {'label': 'NEGATIVE', 'score': 0.9997485280036926},
 {'label': 'POSITIVE', 'score': 0.9907193779945374},
 {'label': 'NEGATIVE', 'score': 0.9991900324821472},
 {'label': 'NEGATIVE', 'score': 0.9960235357284546},
 {'label': 'POSITIVE', 'score': 0.6641486287117004},
 {'label': 'NEGATIVE', 'score': 0.9926788806915283},
 {'label': 'NEGATIVE', 'score': 0.9981911778450012},
 {'label': 'NEGATIVE', 'score': 0.9851551651954651},
 {'label': 'POSITIVE', 'score': 0.9995012283325195},
 {'label': 'NEGATIVE', 'score': 0.5389211177825928},
 {'label': 'NEGATIVE', 'score': 0.9914371371269226},
 {'label': 'NEGATIVE', 'score': 0.9989616870880127},
 {'label': 'NEGATIVE', 'score': 0.9872804284095764},
 {'label': 'POSITIVE', 'score': 0.9997451901435852},
 {'label': 'NEGATIVE', 'score': 0.9939163327217102},
 {'label': 'POSITIVE', 'score': 0.9988551139831543},
 {'label': 'NEGATIVE', 'score': 0.8240289092063904},
 {'label': 'POSITIVE', 'score': 0.8987371921539307},
 {'label': 'NEGATIVE', 'score': 0.8670201301574707},
 {'label': 'POSITIVE', 'score': 0.9937059283256531},
 {'label': 'NEGATIVE', 'score': 0.9861863851547241},
 {'label': 'NEGATIVE', 'score': 0.9983623623847961},
 {'label': 'POSITIVE', 'score': 0.9935332536697388},
 {'label': 'NEGATIVE', 'score': 0.9942175149917603},
 {'label': 'POSITIVE', 'score': 0.9997979998588562},
 {'label': 'POSITIVE', 'score': 0.9854555726051331},
 {'label': 'POSITIVE', 'score': 0.9993767142295837},
 {'label': 'POSITIVE', 'score': 0.8132609128952026},
 {'label': 'NEGATIVE', 'score': 0.9786912202835083},
 {'label': 'POSITIVE', 'score': 0.9990209341049194},
 {'label': 'NEGATIVE', 'score': 0.9912673830986023},
 {'label': 'NEGATIVE', 'score': 0.9865397810935974},
 {'label': 'NEGATIVE', 'score': 0.9991204142570496},
 {'label': 'NEGATIVE', 'score': 0.9989919066429138},
 {'label': 'POSITIVE', 'score': 0.9829335808753967},
 {'label': 'POSITIVE', 'score': 0.9911707639694214},
 {'label': 'NEGATIVE', 'score': 0.609071671962738},
 {'label': 'POSITIVE', 'score': 0.8471978902816772},
 {'label': 'NEGATIVE', 'score': 0.9924693703651428},
 {'label': 'NEGATIVE', 'score': 0.9933571219444275},
 {'label': 'POSITIVE', 'score': 0.7837655544281006},
 {'label': 'POSITIVE', 'score': 0.9997648596763611},
 {'label': 'POSITIVE', 'score': 0.8888156414031982},
 {'label': 'POSITIVE', 'score': 0.9949339032173157},
 {'label': 'NEGATIVE', 'score': 0.9804126620292664},
 {'label': 'POSITIVE', 'score': 0.9905282258987427},
 {'label': 'NEGATIVE', 'score': 0.9840370416641235},
 {'label': 'NEGATIVE', 'score': 0.9955280423164368},
 {'label': 'POSITIVE', 'score': 0.9972652196884155},
 {'label': 'NEGATIVE', 'score': 0.9544557929039001},
 {'label': 'NEGATIVE', 'score': 0.9890429377555847},
 {'label': 'NEGATIVE', 'score': 0.9845442175865173},
 {'label': 'NEGATIVE', 'score': 0.8962046504020691},
 {'label': 'POSITIVE', 'score': 0.9980788230895996},
 {'label': 'NEGATIVE', 'score': 0.9950674772262573},
 {'label': 'NEGATIVE', 'score': 0.9841253757476807},
 {'label': 'POSITIVE', 'score': 0.9952570796012878},
 {'label': 'POSITIVE', 'score': 0.9970357418060303},
 {'label': 'NEGATIVE', 'score': 0.9980165958404541},
 {'label': 'NEGATIVE', 'score': 0.9847229719161987},
 {'label': 'NEGATIVE', 'score': 0.8914454579353333},
 {'label': 'NEGATIVE', 'score': 0.9963845014572144},
 {'label': 'POSITIVE', 'score': 0.9983323216438293},
 {'label': 'NEGATIVE', 'score': 0.9993744492530823},
 {'label': 'POSITIVE', 'score': 0.9968131184577942},
 {'label': 'NEGATIVE', 'score': 0.9842686653137207},
 {'label': 'POSITIVE', 'score': 0.9992997646331787},
 {'label': 'NEGATIVE', 'score': 0.7703074216842651},
 {'label': 'NEGATIVE', 'score': 0.9996874332427979},
 {'label': 'NEGATIVE', 'score': 0.9816251397132874},
 {'label': 'POSITIVE', 'score': 0.9993475079536438},
 {'label': 'NEGATIVE', 'score': 0.9522452354431152},
 {'label': 'POSITIVE', 'score': 0.7724549174308777},
 {'label': 'NEGATIVE', 'score': 0.9921481013298035},
 {'label': 'POSITIVE', 'score': 0.9988489151000977},
 {'label': 'NEGATIVE', 'score': 0.9983319640159607},
 {'label': 'POSITIVE', 'score': 0.9986380934715271},
 {'label': 'NEGATIVE', 'score': 0.9968994855880737},
 {'label': 'NEGATIVE', 'score': 0.9864088296890259},
 {'label': 'NEGATIVE', 'score': 0.9955765008926392},
 {'label': 'POSITIVE', 'score': 0.9896384477615356},
 {'label': 'NEGATIVE', 'score': 0.9963860511779785},
 {'label': 'POSITIVE', 'score': 0.6042464375495911},
 {'label': 'NEGATIVE', 'score': 0.8114780187606812},
 {'label': 'POSITIVE', 'score': 0.8316269516944885},
 {'label': 'POSITIVE', 'score': 0.919884204864502},
 {'label': 'NEGATIVE', 'score': 0.9988634586334229},
 {'label': 'NEGATIVE', 'score': 0.9925756454467773},
 {'label': 'POSITIVE', 'score': 0.9974714517593384},
 {'label': 'POSITIVE', 'score': 0.9910913109779358},
 {'label': 'NEGATIVE', 'score': 0.9745278358459473},
 {'label': 'POSITIVE', 'score': 0.9981983304023743},
 {'label': 'POSITIVE', 'score': 0.929820716381073},
 {'label': 'POSITIVE', 'score': 0.98932284116745},
 {'label': 'POSITIVE', 'score': 0.9886503219604492},
 {'label': 'POSITIVE', 'score': 0.9941171407699585},
 {'label': 'NEGATIVE', 'score': 0.9931461811065674},
 {'label': 'NEGATIVE', 'score': 0.9464724659919739},
 {'label': 'NEGATIVE', 'score': 0.9964673519134521},
 {'label': 'NEGATIVE', 'score': 0.9735369682312012},
 {'label': 'POSITIVE', 'score': 0.9988870024681091},
 {'label': 'NEGATIVE', 'score': 0.9888408780097961},
 {'label': 'NEGATIVE', 'score': 0.9989597797393799},
 {'label': 'NEGATIVE', 'score': 0.9783321022987366},
 {'label': 'POSITIVE', 'score': 0.9996015429496765},
 {'label': 'NEGATIVE', 'score': 0.999242901802063},
 {'label': 'POSITIVE', 'score': 0.9996054768562317},
 {'label': 'NEGATIVE', 'score': 0.9886304140090942},
 {'label': 'NEGATIVE', 'score': 0.971564769744873},
 {'label': 'NEGATIVE', 'score': 0.9993258714675903},
 {'label': 'NEGATIVE', 'score': 0.9993858337402344},
 {'label': 'POSITIVE', 'score': 0.982056200504303},
 {'label': 'POSITIVE', 'score': 0.9968128800392151},
 {'label': 'NEGATIVE', 'score': 0.98362135887146},
 {'label': 'NEGATIVE', 'score': 0.9978548884391785},
 {'label': 'NEGATIVE', 'score': 0.756910502910614},
 {'label': 'NEGATIVE', 'score': 0.8787319660186768},
 {'label': 'POSITIVE', 'score': 0.9974483251571655},
 {'label': 'POSITIVE', 'score': 0.9838787317276001},
 {'label': 'NEGATIVE', 'score': 0.9989644289016724},
 {'label': 'POSITIVE', 'score': 0.9824825525283813},
 {'label': 'NEGATIVE', 'score': 0.9795563220977783},
 {'label': 'NEGATIVE', 'score': 0.9828624129295349},
 {'label': 'POSITIVE', 'score': 0.9995749592781067},
 {'label': 'POSITIVE', 'score': 0.6642239689826965},
 {'label': 'NEGATIVE', 'score': 0.9988778233528137},
 {'label': 'NEGATIVE', 'score': 0.991527259349823},
 {'label': 'NEGATIVE', 'score': 0.9996930360794067},
 {'label': 'POSITIVE', 'score': 0.999806821346283},
 {'label': 'NEGATIVE', 'score': 0.9723715782165527},
 {'label': 'POSITIVE', 'score': 0.9949198365211487},
 {'label': 'NEGATIVE', 'score': 0.9978474378585815},
 {'label': 'NEGATIVE', 'score': 0.9618366956710815},
 {'label': 'POSITIVE', 'score': 0.986754834651947},
 {'label': 'NEGATIVE', 'score': 0.9984903335571289},
 {'label': 'NEGATIVE', 'score': 0.9950502514839172},
 {'label': 'POSITIVE', 'score': 0.506658673286438},
 {'label': 'POSITIVE', 'score': 0.9254662990570068},
 {'label': 'POSITIVE', 'score': 0.9757055640220642},
 {'label': 'NEGATIVE', 'score': 0.9992293119430542},
 {'label': 'NEGATIVE', 'score': 0.998879611492157},
 {'label': 'NEGATIVE', 'score': 0.9304995536804199},
 {'label': 'NEGATIVE', 'score': 0.9974313378334045},
 {'label': 'POSITIVE', 'score': 0.9977074861526489},
 {'label': 'POSITIVE', 'score': 0.9993116855621338},
 {'label': 'NEGATIVE', 'score': 0.9778060913085938},
 {'label': 'NEGATIVE', 'score': 0.9428784847259521},
 {'label': 'POSITIVE', 'score': 0.9986544847488403},
 {'label': 'POSITIVE', 'score': 0.9946094751358032},
 {'label': 'POSITIVE', 'score': 0.9987550973892212},
 {'label': 'NEGATIVE', 'score': 0.9956972599029541},
 {'label': 'NEGATIVE', 'score': 0.995010256767273},
 {'label': 'POSITIVE', 'score': 0.9961000680923462},
 {'label': 'POSITIVE', 'score': 0.9840848445892334},
 {'label': 'POSITIVE', 'score': 0.7224017977714539},
 {'label': 'NEGATIVE', 'score': 0.9937185049057007},
 {'label': 'POSITIVE', 'score': 0.9955014586448669},
 {'label': 'POSITIVE', 'score': 0.6914131045341492},

In [ ]:
df1["Sentiment"] = [result["label"] for result in results]
df1["Score"] = [result["score"] for result in results]

/tmp/ipython-input-3946832451.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1["Sentiment"] = [result["label"] for result in results]
/tmp/ipython-input-3946832451.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1["Score"] = [result["score"] for result in results]

In [ ]:
df1.head()

,id,screen_name,time,link,text,source,user_id,date_file,account_id,account_screen_name,account_account_type,meta_name,meta_chamber,meta_type,meta_party,Clean_Text,Sentiment,Score
0,877383834240667648,KamalaHarris,2017-06-21 00:33:01-04:00,https://www.twitter.com/KamalaHarris/statuses/...,No public hearings. \nNo debate. \nNo text.\nN...,Sprout Social,30354991,2017-06-21.json,30354991,KamalaHarris,campaign,Kamala Harris,senate,member,D,no public hearings no debate no textno transpa...,NEGATIVE,0.997041
1,877376225664090112,tedlieu,2017-06-21 00:02:47-04:00,https://www.twitter.com/tedlieu/statuses/87737...,Why should world leaders trust or listen to US...,Twitter for Android,21059255,2017-06-21.json,21059255,tedlieu,campaign,Ted Lieu,house,member,D,why should world leaders trust or listen to us...,NEGATIVE,0.998634
2,877405817565306880,JerryNadler,2017-06-21 02:00:22-04:00,https://www.twitter.com/JerryNadler/statuses/8...,Congratulations to Jon @ossoff and #GADems on ...,Twitter for iPhone,408816873,2017-06-21.json,408816873,JerryNadler,campaign,Jerrold Nadler,house,member,D,congratulations to jon <OTHER_USER> and gadems...,POSITIVE,0.899538
3,877400668411052032,TulsiGabbard,2017-06-21 01:39:55-04:00,https://www.twitter.com/TulsiGabbard/statuses/...,Join me in celebrating the gift of yoga on thi...,Twitter for iPhone,26637348,2017-06-21.json,26637348,TulsiGabbard,campaign,Tulsi Gabbard,house,member,D,join me in celebrating the gift of yoga on thi...,POSITIVE,0.999664
4,877409109846478848,JerryNadler,2017-06-21 02:13:27-04:00,https://www.twitter.com/JerryNadler/statuses/8...,#GA06 is #GOP stronghold &amp; @ossoff nearly ...,Twitter for iPhone,408816873,2017-06-21.json,408816873,JerryNadler,campaign,Jerrold Nadler,house,member,D,ga06 is gop stronghold amp <OTHER_USER> nearly...,POSITIVE,0.983245

In [ ]:
df1.to_csv("df1.csv")

In [ ]:
#supervised fine tuning, rlhf, create ai agent to tweet or maybe scan tweets for factuality